# Travis CI build file

language: java
jdk:
    - oraclejdk8

before_script: 
    - pwd
script:
    # This bypasses an issue on the travis CI platform where a connection is made through a proxy and
    # the mirror redirection is not handled correctly by one of the parties.
    - mvn p2:site -f lib/uk.ac.kcl.mdeoptimise.lib/pom.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
    - mvn -f src/pom.xml clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true

    - mvn -f src/pom.xml test
