# Travis CI build file

language: java
jdk:
    - oraclejdk8

cache:
      directories:
             - $HOME/.m2
before_script: 
    - cd src
    - pwd
script:
    # This bypasses an issue on the travis CI platform where a connection is made through a proxy and
    # the mirror redirection is not handled correctly by one of the parties.
    - mvn clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
    - mvn test
