# Travis CI build file

language: java
jdk:
    - oraclejdk8

before_script: 
    - cd src/
    - pwd
script:
    - mvn clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
    - mvn test
